-- AlterTable
ALTER TABLE "review_scores" ALTER COLUMN "selfScore" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "managerScore" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "hrScore" SET DATA TYPE DOUBLE PRECISION;
