/**
 * @file taskGoalTemplates.js
 * @description Enterprise-grade Goal and Task seed templates covering all statuses,
 * departments, and financial years: FY 2024-25, FY 2025-26 & FY 2026-27.
 *
 * Rules strictly followed:
 * 1. Tasks under each Goal sum to exactly 100% weight (satisfying goalWeight.service.js).
 * 2. Covers all TaskBoard columns: 'todo', 'in_progress', 'pending_on_others', 'in_review', 'done'.
 * 3. Covers all Goal statuses: 'DRAFT', 'ACTIVE', 'IN_PROGRESS', 'PENDING_MANAGER_REVIEW', 'PENDING_HR_REVIEW', 'COMPLETED'.
 * 4. Critical tasks include TaskMilestone records with realistic watcher emails and order.
 * 5. 'pending_on_others' tasks include structured dependency JSON metadata.
 */

export const DEPARTMENT_TEMPLATES = {
  Engineering: {
    'FY 2024-25': [
      {
        goal: {
          title: 'Monolithic Decomposition & REST API Gateway Standardization',
          description: 'Refactor legacy monolithic services into decoupled micro-modules, deploy centralized API gateway, and document OpenAPI v3 specifications.',
          category: 'Technical Skills',
          priority: 'high',
          goalType: 'General',
          status: 'COMPLETED',
          quarter: 'Q2',
          progress: 100,
          startDate: '2024-04-01T00:00:00.000Z',
          targetDate: '2024-09-30T00:00:00.000Z',
          dueDate: '2024-09-30T00:00:00.000Z',
          milestones: 4,
          completedMilestones: 4,
        },
        tasks: [
          {
            title: 'Audit Legacy Monolith Codebase & Map Service Domain Boundaries',
            description: 'Analyze database couplings, extract shared utility packages, and establish domain boundaries for auth, leave, and task modules.',
            priority: 'medium',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2024-04-05T00:00:00.000Z',
            dueDate: '2024-05-15T00:00:00.000Z',
            actualStartDate: '2024-04-06T00:00:00.000Z',
            actualCompletionDate: '2024-05-12T00:00:00.000Z',
            tags: 'Architecture,Monolith,Refactor',
          },
          {
            title: 'Deploy Kong API Gateway with Distributed JWT Authentication',
            description: 'Configure rate limiting plugins, route token decoding, and establish automated CORS origin validation at the edge proxy.',
            priority: 'high',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2024-05-16T00:00:00.000Z',
            dueDate: '2024-06-30T00:00:00.000Z',
            actualStartDate: '2024-05-18T00:00:00.000Z',
            actualCompletionDate: '2024-06-25T00:00:00.000Z',
            tags: 'Gateway,Security,JWT',
          },
          {
            title: 'Extract User Identity & Session Storage into Standalone Service',
            description: 'Decouple session tables from core database, migrate auth verification logic to redis-backed tokens, and verify token refresh lifecycles.',
            priority: 'critical',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2024-07-01T00:00:00.000Z',
            dueDate: '2024-08-15T00:00:00.000Z',
            actualStartDate: '2024-07-03T00:00:00.000Z',
            actualCompletionDate: '2024-08-14T00:00:00.000Z',
            tags: 'Auth,Microservices,Redis',
          },
          {
            title: 'Benchmark API Response Latency Under Synthetic Peak Load',
            description: 'Execute k6 load test scripts simulating 5,000 concurrent requests and verify p95 latency remains under 80 milliseconds.',
            priority: 'medium',
            status: 'in_review',
            progress: 90,
            weight: 20,
            startDate: '2024-08-16T00:00:00.000Z',
            dueDate: '2024-09-15T00:00:00.000Z',
            actualStartDate: '2024-08-18T00:00:00.000Z',
            tags: 'LoadTesting,k6,Performance',
          },
          {
            title: 'Deprecate Monolithic V1 Endpoints & Publish Developer API Migration Guide',
            description: 'Document breaking changes in Swagger hub, notify client integration teams, and sunset legacy endpoints.',
            priority: 'low',
            status: 'todo',
            progress: 0,
            weight: 20,
            startDate: '2024-09-15T00:00:00.000Z',
            dueDate: '2024-09-30T00:00:00.000Z',
            tags: 'Docs,API,Deprecation',
          },
        ],
      },
      {
        goal: {
          title: 'Automated Integration Testing & E2E Test Suite Automation',
          description: 'Deploy headless Playwright test runners in GitHub Actions, enforce minimum 80% coverage on critical paths, and eradicate flaky tests.',
          category: 'Product Innovation',
          priority: 'critical',
          goalType: 'General',
          status: 'COMPLETED',
          quarter: 'Q4',
          progress: 100,
          startDate: '2024-10-01T00:00:00.000Z',
          targetDate: '2025-03-31T00:00:00.000Z',
          dueDate: '2025-03-31T00:00:00.000Z',
          milestones: 4,
          completedMilestones: 4,
        },
        tasks: [
          {
            title: 'Implement Playwright Cross-Browser End-to-End Test Suite',
            description: 'Cover full user lifecycle: login, goal assignment, task state changes, and leave approvals across Chromium, Firefox, and WebKit.',
            priority: 'high',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2024-10-08T00:00:00.000Z',
            dueDate: '2024-11-20T00:00:00.000Z',
            actualStartDate: '2024-10-10T00:00:00.000Z',
            actualCompletionDate: '2024-11-18T00:00:00.000Z',
            tags: 'E2E,Playwright,Testing',
          },
          {
            title: 'Containerize Headless Chromium Runners for Parallel CI Matrix',
            description: 'Shard test executions across 4 parallel containers to reduce PR feedback turnaround time from 22 minutes to under 6 minutes.',
            priority: 'medium',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2024-11-22T00:00:00.000Z',
            dueDate: '2024-12-28T00:00:00.000Z',
            actualStartDate: '2024-11-25T00:00:00.000Z',
            actualCompletionDate: '2024-12-24T00:00:00.000Z',
            tags: 'Docker,CI,Parallel',
          },
          {
            title: 'Configure Code Coverage Reporting Gates in Pull Request Checks',
            description: 'Integrate Codecov assertions to block merges if patch coverage falls below 85% on backend services.',
            priority: 'medium',
            status: 'in_review',
            progress: 85,
            weight: 20,
            startDate: '2025-01-05T00:00:00.000Z',
            dueDate: '2025-02-15T00:00:00.000Z',
            actualStartDate: '2025-01-08T00:00:00.000Z',
            tags: 'Coverage,SonarQube,QA',
          },
          {
            title: 'Coordinate Staging Environment Data Masking & Golden Master Seeds',
            description: 'Implement automated PII masking scripts to populate staging database with production-like sanitized test datasets.',
            priority: 'critical',
            status: 'pending_on_others',
            progress: 30,
            weight: 20,
            startDate: '2025-02-01T00:00:00.000Z',
            dueDate: '2025-03-10T00:00:00.000Z',
            tags: 'Staging,DataMasking,Security',
            dependencyRequiresManager: true,
            dependencyTitle: 'Waiting on Data Protection Officer (DPO) Approval for Masking Scripts',
            isMilestoneTracked: true,
            milestones: [
              { order: 1, title: 'Draft PII identification regex rules', dueDate: '2025-02-10T00:00:00.000Z', status: 'DONE', isDone: true },
              { order: 2, title: 'Test data scrubbing script on staging sandbox', dueDate: '2025-02-25T00:00:00.000Z', status: 'APPROVED', isDone: true },
              { order: 3, title: 'Final DPO compliance verification check', dueDate: '2025-03-08T00:00:00.000Z', status: 'PENDING_APPROVAL', isDone: false },
            ],
          },
          {
            title: 'Deploy Flaky Test Quarantine Workflow & Slack Failure Alerts',
            description: 'Automatically isolate intermittent failures into a separate quarantine pipeline to prevent blocking production releases.',
            priority: 'low',
            status: 'in_progress',
            progress: 50,
            weight: 20,
            startDate: '2025-02-15T00:00:00.000Z',
            dueDate: '2025-03-31T00:00:00.000Z',
            actualStartDate: '2025-02-18T00:00:00.000Z',
            tags: 'FlakyTests,Monitoring,Slack',
          },
        ],
      },
    ],
    'FY 2025-26': [
      {
        goal: {
          title: 'Enterprise Cloud Infrastructure Modernization & Scalability',
          description: 'Migrate core backend workloads to containerized infrastructure, optimize cloud cost efficiency, and implement continuous delivery pipelines.',
          category: 'Technical Skills',
          priority: 'critical',
          goalType: 'General',
          status: 'COMPLETED',
          quarter: 'Q2',
          progress: 100,
          startDate: '2025-04-01T00:00:00.000Z',
          targetDate: '2025-09-30T00:00:00.000Z',
          dueDate: '2025-09-30T00:00:00.000Z',
          milestones: 4,
          completedMilestones: 4,
        },
        tasks: [
          {
            title: 'Design VPC Network Topology & Zero-Trust IAM Access Policies',
            description: 'Establish isolated subnets, transit gateway routes, and least-privilege service account roles for production clusters.',
            priority: 'critical',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2025-04-05T00:00:00.000Z',
            dueDate: '2025-05-15T00:00:00.000Z',
            actualStartDate: '2025-04-06T00:00:00.000Z',
            actualCompletionDate: '2025-05-14T00:00:00.000Z',
            tags: 'DevOps,Security,VPC',
            isMilestoneTracked: true,
            milestones: [
              { order: 1, title: 'Draft subnet topology specification', dueDate: '2025-04-18T00:00:00.000Z', status: 'DONE', isDone: true },
              { order: 2, title: 'Peer review IAM security boundaries', dueDate: '2025-05-02T00:00:00.000Z', status: 'DONE', isDone: true },
              { order: 3, title: 'Apply Terraform scripts to staging', dueDate: '2025-05-14T00:00:00.000Z', status: 'DONE', isDone: true },
            ],
          },
          {
            title: 'Containerize Core Microservices with Multi-Stage Docker Builds',
            description: 'Optimize image layers, reduce artifact attack surface (<80MB per image), and enforce non-root container runtimes.',
            priority: 'high',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2025-05-16T00:00:00.000Z',
            dueDate: '2025-06-30T00:00:00.000Z',
            actualStartDate: '2025-05-18T00:00:00.000Z',
            actualCompletionDate: '2025-06-28T00:00:00.000Z',
            tags: 'Docker,Containers,Backend',
          },
          {
            title: 'Implement Multi-Environment Automated CI/CD Deploy Pipelines',
            description: 'Create GitHub Actions workflows with automated semantic versioning, container vulnerability scanning, and rollback hooks.',
            priority: 'high',
            status: 'in_review',
            progress: 90,
            weight: 20,
            startDate: '2025-07-01T00:00:00.000Z',
            dueDate: '2025-08-15T00:00:00.000Z',
            actualStartDate: '2025-07-02T00:00:00.000Z',
            tags: 'CI/CD,Automation,Testing',
          },
          {
            title: 'Configure Distributed Redis Cluster & PostgreSQL Connection Pooling',
            description: 'Implement read-replica routing with PgBouncer, cache cacheable read queries, and tune transaction timeout thresholds.',
            priority: 'medium',
            status: 'in_progress',
            progress: 60,
            weight: 20,
            startDate: '2025-08-16T00:00:00.000Z',
            dueDate: '2025-09-15T00:00:00.000Z',
            actualStartDate: '2025-08-18T00:00:00.000Z',
            tags: 'Database,Redis,Optimization',
          },
          {
            title: 'Execute Automated Chaos Engineering Drills & DR Failover Tests',
            description: 'Simulate zone outage failures, verify database failover time under 30 seconds, and document recovery time objectives (RTO).',
            priority: 'low',
            status: 'todo',
            progress: 0,
            weight: 20,
            startDate: '2025-09-15T00:00:00.000Z',
            dueDate: '2025-09-30T00:00:00.000Z',
            tags: 'Chaos,DisasterRecovery,QA',
          },
        ],
      },
      {
        goal: {
          title: 'Core Web Vitals SLA & Modular Frontend Architecture Overhaul',
          description: 'Rebuild dashboard visualization components, improve Largest Contentful Paint (LCP) under 1.8s, and eliminate UI bundle bloat.',
          category: 'Product Innovation',
          priority: 'high',
          goalType: 'General',
          status: 'ACTIVE',
          quarter: 'Q4',
          progress: 75,
          startDate: '2025-10-01T00:00:00.000Z',
          targetDate: '2026-03-31T00:00:00.000Z',
          dueDate: '2026-03-31T00:00:00.000Z',
          milestones: 4,
          completedMilestones: 3,
        },
        tasks: [
          {
            title: 'Audit Web Performance Bottlenecks & Code-Split Large Route Chunks',
            description: 'Use Chrome DevTools performance traces and Webpack bundle analyzer to extract common vendor chunks and defer non-critical CSS.',
            priority: 'high',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2025-10-05T00:00:00.000Z',
            dueDate: '2025-11-15T00:00:00.000Z',
            actualStartDate: '2025-10-06T00:00:00.000Z',
            actualCompletionDate: '2025-11-14T00:00:00.000Z',
            tags: 'Frontend,Performance,Vite',
          },
          {
            title: 'Migrate Legacy Dashboard Tables to Virtualized Grid Component',
            description: 'Replace standard DOM table rendering with windowed virtualization to smoothly handle 10,000+ data records without frame drops.',
            priority: 'medium',
            status: 'in_review',
            progress: 85,
            weight: 20,
            startDate: '2025-11-16T00:00:00.000Z',
            dueDate: '2025-12-31T00:00:00.000Z',
            actualStartDate: '2025-11-18T00:00:00.000Z',
            tags: 'UI,React,Virtualization',
          },
          {
            title: 'Implement Resilient WebSocket Reconnect Logic & Channel Subscriptions',
            description: 'Support automatic exponential backoff reconnection, offline message queues, and heartbeats for real-time leave/task events.',
            priority: 'high',
            status: 'in_progress',
            progress: 55,
            weight: 20,
            startDate: '2026-01-05T00:00:00.000Z',
            dueDate: '2026-02-15T00:00:00.000Z',
            actualStartDate: '2026-01-08T00:00:00.000Z',
            tags: 'WebSocket,Realtime,Networking',
          },
          {
            title: 'Coordinate 3rd-Party CDN Edge Caching & SSL Origin Certificates',
            description: 'Configure Cloudflare edge caching rules, geo-distributed assets, and origin request routing with DevOps security team.',
            priority: 'critical',
            status: 'pending_on_others',
            progress: 25,
            weight: 20,
            startDate: '2026-02-01T00:00:00.000Z',
            dueDate: '2026-03-10T00:00:00.000Z',
            tags: 'CDN,Edge,Cloudflare',
            dependencyRequiresManager: true,
            dependencyTitle: 'Awaiting CDN Origin Certificate Validation from Infrastructure Team',
            isMilestoneTracked: true,
            milestones: [
              { order: 1, title: 'Issue SSL Certificate signing request (CSR)', dueDate: '2026-02-10T00:00:00.000Z', status: 'DONE', isDone: true },
              { order: 2, title: 'Edge routing DNS propagation test', dueDate: '2026-02-25T00:00:00.000Z', status: 'PENDING_APPROVAL', isDone: false },
              { order: 3, title: 'Staging edge cache hit-rate verification', dueDate: '2026-03-08T00:00:00.000Z', status: 'PENDING_APPROVAL', isDone: false },
            ],
          },
          {
            title: 'Integrate Lighthouse CI Score Gating in Main Branch Pull Requests',
            description: 'Enforce minimum Performance score >= 90 and Accessibility score >= 95 before merging feature branches.',
            priority: 'low',
            status: 'todo',
            progress: 0,
            weight: 20,
            startDate: '2026-03-01T00:00:00.000Z',
            dueDate: '2026-03-31T00:00:00.000Z',
            tags: 'Lighthouse,QA,CI',
          },
        ],
      },
    ],
    'FY 2026-27': [
      {
        goal: {
          title: 'AI-Driven Predictive Analytics Engine & Automated Insights',
          description: 'Deploy embedded machine learning models for workforce capacity forecasting, milestone delay prediction, and automated anomaly alerts.',
          category: 'Product Innovation',
          priority: 'critical',
          goalType: 'General',
          status: 'ACTIVE',
          quarter: 'Q2',
          progress: 50,
          startDate: '2026-04-01T00:00:00.000Z',
          targetDate: '2026-09-30T00:00:00.000Z',
          dueDate: '2026-09-30T00:00:00.000Z',
          milestones: 4,
          completedMilestones: 2,
        },
        tasks: [
          {
            title: 'Design Model Feature Store & Historical Task Completion Pipelines',
            description: 'Extract cleansed completion velocity metrics, developer throughput patterns, and task dependency graphs into parquet stores.',
            priority: 'high',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2026-04-05T00:00:00.000Z',
            dueDate: '2026-05-15T00:00:00.000Z',
            actualStartDate: '2026-04-06T00:00:00.000Z',
            actualCompletionDate: '2026-05-12T00:00:00.000Z',
            tags: 'AI,DataPipeline,Python',
          },
          {
            title: 'Train & Fine-Tune Milestone Escalation Risk Classifier',
            description: 'Train XGBoost/LightGBM model to predict milestone slip probability based on complexity, assignee load, and past velocity.',
            priority: 'critical',
            status: 'in_progress',
            progress: 65,
            weight: 20,
            startDate: '2026-05-16T00:00:00.000Z',
            dueDate: '2026-06-30T00:00:00.000Z',
            actualStartDate: '2026-05-18T00:00:00.000Z',
            tags: 'MachineLearning,Predictive,Escalation',
            isMilestoneTracked: true,
            milestones: [
              { order: 1, title: 'Dataset curation and train/test split', dueDate: '2026-05-28T00:00:00.000Z', status: 'DONE', isDone: true },
              { order: 2, title: 'Cross-validation accuracy benchmark (>88%)', dueDate: '2026-06-15T00:00:00.000Z', status: 'APPROVED', isDone: true },
              { order: 3, title: 'Low-latency ONNX model export', dueDate: '2026-06-28T00:00:00.000Z', status: 'PENDING_APPROVAL', isDone: false },
            ],
          },
          {
            title: 'Await Security & Data Privacy Compliance Review for ML Pipeline',
            description: 'Conduct Data Protection Impact Assessment (DPIA) with Legal & Compliance team for employee metric inference.',
            priority: 'high',
            status: 'pending_on_others',
            progress: 40,
            weight: 20,
            startDate: '2026-06-15T00:00:00.000Z',
            dueDate: '2026-07-20T00:00:00.000Z',
            tags: 'Compliance,Privacy,DPIA',
            dependencyRequiresManager: true,
            dependencyTitle: 'Pending Privacy & Data Ethics Sign-off from Legal Counsel',
          },
          {
            title: 'Expose REST & gRPC Inference Endpoints with Rate Limiting',
            description: 'Build fast inference service with caching layer and Prometheus instrumentation for p99 latency monitoring under 45ms.',
            priority: 'medium',
            status: 'in_review',
            progress: 80,
            weight: 20,
            startDate: '2026-07-15T00:00:00.000Z',
            dueDate: '2026-08-30T00:00:00.000Z',
            actualStartDate: '2026-07-18T00:00:00.000Z',
            tags: 'API,gRPC,Microservices',
          },
          {
            title: 'Build Executive Predictive Risk Widget in CXO Connect Dashboard',
            description: 'Deliver visual confidence gauge, projected deadline slip dates, and automated corrective suggestions on web UI.',
            priority: 'medium',
            status: 'todo',
            progress: 0,
            weight: 20,
            startDate: '2026-08-25T00:00:00.000Z',
            dueDate: '2026-09-30T00:00:00.000Z',
            tags: 'UI,Dashboard,Analytics',
          },
        ],
      },
    ],
  },

  IT: {
    'FY 2024-25': [
      {
        goal: {
          title: 'Enterprise Identity Governance & Cloud Directory Consolidation',
          description: 'Migrate on-prem Active Directory forests to cloud identity provider, enforce universal single sign-on, and automate user offboarding.',
          category: 'Compliance & Security',
          priority: 'critical',
          goalType: 'General',
          status: 'COMPLETED',
          quarter: 'Q3',
          progress: 100,
          startDate: '2024-05-01T00:00:00.000Z',
          targetDate: '2024-11-30T00:00:00.000Z',
          dueDate: '2024-11-30T00:00:00.000Z',
          milestones: 4,
          completedMilestones: 4,
        },
        tasks: [
          {
            title: 'Consolidate Active Directory Domains to Azure AD / Entra ID',
            description: 'Map user groups, synchronize password hashes with Azure AD Connect, and resolve user principal name collisions.',
            priority: 'high',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2024-05-10T00:00:00.000Z',
            dueDate: '2024-06-30T00:00:00.000Z',
            actualStartDate: '2024-05-12T00:00:00.000Z',
            actualCompletionDate: '2024-06-26T00:00:00.000Z',
            tags: 'ActiveDirectory,CloudIdentity,SSO',
          },
          {
            title: 'Enforce Centralized RBAC Security Groups & Access Reviews',
            description: 'Implement quarterly access recertification campaigns to prevent privilege creep across developer and support accounts.',
            priority: 'medium',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2024-07-01T00:00:00.000Z',
            dueDate: '2024-08-20T00:00:00.000Z',
            actualStartDate: '2024-07-04T00:00:00.000Z',
            actualCompletionDate: '2024-08-18T00:00:00.000Z',
            tags: 'RBAC,AccessReview,Security',
          },
          {
            title: 'Deploy Automated Single Sign-On (SSO) for 3rd-Party SaaS Apps',
            description: 'Configure SAML 2.0 / OIDC integrations for Jira, Slack, Figma, and GitHub Enterprise with automated SCIM provisioning.',
            priority: 'high',
            status: 'in_review',
            progress: 90,
            weight: 20,
            startDate: '2024-08-25T00:00:00.000Z',
            dueDate: '2024-10-15T00:00:00.000Z',
            actualStartDate: '2024-08-28T00:00:00.000Z',
            tags: 'SAML,SCIM,SaaS',
          },
          {
            title: 'Coordinate Legacy LDAP Deprecation with Network Security Team',
            description: 'Decommission legacy LDAP servers and migrate internal printers and NAS storage appliances to modern Kerberos/OIDC.',
            priority: 'critical',
            status: 'pending_on_others',
            progress: 25,
            weight: 20,
            startDate: '2024-10-01T00:00:00.000Z',
            dueDate: '2024-11-15T00:00:00.000Z',
            tags: 'LDAP,Legacy,Decommission',
            dependencyRequiresManager: true,
            dependencyTitle: 'Pending Network Firewall Rule Transition from Infosec Team',
          },
          {
            title: 'Publish IT Identity Helpdesk Guidelines & Self-Service Password Reset (SSPR)',
            description: 'Deploy self-service password reset portal with SMS/Authenticator challenge verification, reducing IT ticket volume by 35%.',
            priority: 'low',
            status: 'todo',
            progress: 0,
            weight: 20,
            startDate: '2024-11-15T00:00:00.000Z',
            dueDate: '2024-11-30T00:00:00.000Z',
            tags: 'SSPR,Helpdesk,SelfService',
          },
        ],
      },
    ],
    'FY 2025-26': [
      {
        goal: {
          title: 'Enterprise Cyber Security Hardening & Zero-Trust Architecture',
          description: 'Deploy multi-factor hardware security tokens, automate patch management across all fleet workstations, and pass SOC2 Type II audit.',
          category: 'Compliance & Security',
          priority: 'critical',
          goalType: 'General',
          status: 'COMPLETED',
          quarter: 'Q3',
          progress: 100,
          startDate: '2025-05-01T00:00:00.000Z',
          targetDate: '2025-11-30T00:00:00.000Z',
          dueDate: '2025-11-30T00:00:00.000Z',
          milestones: 4,
          completedMilestones: 4,
        },
        tasks: [
          {
            title: 'Roll Out Hardware FIDO2 Security Keys & Enforce SSO WebAuthn',
            description: 'Provision YubiKeys to all engineers, deprecate SMS MFA, and enforce conditional access policies on tenant domain.',
            priority: 'critical',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2025-05-10T00:00:00.000Z',
            dueDate: '2025-06-30T00:00:00.000Z',
            actualStartDate: '2025-05-12T00:00:00.000Z',
            actualCompletionDate: '2025-06-25T00:00:00.000Z',
            tags: 'Security,MFA,ZeroTrust',
          },
          {
            title: 'Configure Centralized SIEM Log Aggregation & Real-time Intrusion Detection',
            description: 'Ship audit logs from Kubernetes, Postgres, and CloudTrail to OpenSearch cluster with automated alerting thresholds.',
            priority: 'high',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2025-07-01T00:00:00.000Z',
            dueDate: '2025-08-20T00:00:00.000Z',
            actualStartDate: '2025-07-03T00:00:00.000Z',
            actualCompletionDate: '2025-08-18T00:00:00.000Z',
            tags: 'SIEM,Logging,Monitoring',
          },
          {
            title: 'Perform Annual Penetration Testing & Remediate Critical Vulnerabilities',
            description: 'Contract third-party security auditors for black-box penetration testing on public web endpoints and API gateway.',
            priority: 'critical',
            status: 'in_review',
            progress: 90,
            weight: 20,
            startDate: '2025-08-25T00:00:00.000Z',
            dueDate: '2025-10-15T00:00:00.000Z',
            actualStartDate: '2025-08-28T00:00:00.000Z',
            tags: 'PenTest,Audit,Security',
          },
          {
            title: 'Coordinate Annual Endpoint Anti-Virus License Renewal & Deployment',
            description: 'Procure updated EDR licenses and push agent updates across remote and office developer laptops.',
            priority: 'medium',
            status: 'pending_on_others',
            progress: 30,
            weight: 20,
            startDate: '2025-10-01T00:00:00.000Z',
            dueDate: '2025-11-10T00:00:00.000Z',
            tags: 'EDR,Antivirus,Licensing',
            dependencyRequiresManager: true,
            dependencyTitle: 'Pending Purchase Order Approval from Finance Department',
          },
          {
            title: 'Publish Comprehensive Employee Security Awareness & Phishing Simulation',
            description: 'Conduct simulated phishing campaign, measure employee failure rate (<3%), and assign refresher training modules.',
            priority: 'low',
            status: 'todo',
            progress: 0,
            weight: 20,
            startDate: '2025-11-10T00:00:00.000Z',
            dueDate: '2025-11-30T00:00:00.000Z',
            tags: 'Training,Compliance,Phishing',
          },
        ],
      },
    ],
    'FY 2026-27': [
      {
        goal: {
          title: 'High-Availability Database Clustering & Automated Point-in-Time Recovery',
          description: 'Establish cross-region replication for PostgreSQL, implement automated hourly WAL backups, and achieve 99.99% uptime SLA.',
          category: 'Technical Skills',
          priority: 'high',
          goalType: 'General',
          status: 'ACTIVE',
          quarter: 'Q1',
          progress: 45,
          startDate: '2026-04-01T00:00:00.000Z',
          targetDate: '2026-08-31T00:00:00.000Z',
          dueDate: '2026-08-31T00:00:00.000Z',
          milestones: 3,
          completedMilestones: 1,
        },
        tasks: [
          {
            title: 'Benchmark Managed PostgreSQL v16 Engine Upgrades & Extensions',
            description: 'Spin up staging clone, run stress test suite, and verify query performance regression for JSONB and geospatial extensions.',
            priority: 'medium',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2026-04-10T00:00:00.000Z',
            dueDate: '2026-05-15T00:00:00.000Z',
            actualStartDate: '2026-04-12T00:00:00.000Z',
            actualCompletionDate: '2026-05-14T00:00:00.000Z',
            tags: 'Postgres,Database,Upgrade',
          },
          {
            title: 'Deploy Cross-AZ Hot Standby Streaming Replication',
            description: 'Configure asynchronous physical streaming replication with automated Patroni quorum failover on network partitions.',
            priority: 'high',
            status: 'in_progress',
            progress: 50,
            weight: 20,
            startDate: '2026-05-16T00:00:00.000Z',
            dueDate: '2026-06-30T00:00:00.000Z',
            actualStartDate: '2026-05-20T00:00:00.000Z',
            tags: 'Replication,HighAvailability,Database',
          },
          {
            title: 'Verify Offsite Encrypted Object Storage Backups with Cold Storage Tiers',
            description: 'Automate pgBackRest multi-threaded backup transfers to immutable S3 buckets with Glacier archival retention rules.',
            priority: 'critical',
            status: 'pending_on_others',
            progress: 20,
            weight: 20,
            startDate: '2026-06-15T00:00:00.000Z',
            dueDate: '2026-07-25T00:00:00.000Z',
            tags: 'Backups,S3,pgBackRest',
            dependencyRequiresManager: true,
            dependencyTitle: 'Waiting on Cloud Storage Quota Increase from AWS Support',
          },
          {
            title: 'Execute Point-in-Time Recovery (PITR) Drill on Production Replica',
            description: 'Restore database to a precise microsecond state 14 days in the past and measure table data consistency checksums.',
            priority: 'high',
            status: 'in_review',
            progress: 80,
            weight: 20,
            startDate: '2026-07-15T00:00:00.000Z',
            dueDate: '2026-08-15T00:00:00.000Z',
            actualStartDate: '2026-07-16T00:00:00.000Z',
            tags: 'Recovery,PITR,Validation',
          },
          {
            title: 'Publish Comprehensive Runbook for Database Outages & Ops Training',
            description: 'Create step-by-step incident response playbook in Company Hub with escalation hierarchies and command checklists.',
            priority: 'low',
            status: 'todo',
            progress: 0,
            weight: 20,
            startDate: '2026-08-16T00:00:00.000Z',
            dueDate: '2026-08-31T00:00:00.000Z',
            tags: 'Docs,Runbook,Operations',
          },
        ],
      },
    ],
  },

  Operations: {
    'FY 2024-25': [
      {
        goal: {
          title: 'Operational Quality Assurance & Incident Management Standardization',
          description: 'Establish Tier-1 through Tier-3 escalation trees, automate paging for system outages, and reduce mean time to resolution (MTTR) by 45%.',
          category: 'Business Operations',
          priority: 'high',
          goalType: 'General',
          status: 'COMPLETED',
          quarter: 'Q3',
          progress: 100,
          startDate: '2024-06-01T00:00:00.000Z',
          targetDate: '2024-12-31T00:00:00.000Z',
          dueDate: '2024-12-31T00:00:00.000Z',
          milestones: 4,
          completedMilestones: 4,
        },
        tasks: [
          {
            title: 'Establish Tier-1 to Tier-3 Incident Classification Matrix',
            description: 'Formalize severity definitions, response time commitments, and triage checklists across support engineers.',
            priority: 'medium',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2024-06-10T00:00:00.000Z',
            dueDate: '2024-07-20T00:00:00.000Z',
            actualStartDate: '2024-06-12T00:00:00.000Z',
            actualCompletionDate: '2024-07-18T00:00:00.000Z',
            tags: 'Incidents,Classification,Ops',
          },
          {
            title: 'Implement PagerDuty On-Call Rotations & Automated Escalation Policies',
            description: 'Configure multi-layer escalation rules with phone call fallbacks for severity-1 outages during non-business hours.',
            priority: 'high',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2024-07-25T00:00:00.000Z',
            dueDate: '2024-09-10T00:00:00.000Z',
            actualStartDate: '2024-07-28T00:00:00.000Z',
            actualCompletionDate: '2024-09-08T00:00:00.000Z',
            tags: 'PagerDuty,OnCall,Automation',
          },
          {
            title: 'Conduct Quarterly Post-Mortem Root Cause Analysis (RCA) Reviews',
            description: 'Facilitate blameless post-mortem sessions, track action items in Jira, and share learnings across engineering leads.',
            priority: 'medium',
            status: 'in_review',
            progress: 85,
            weight: 20,
            startDate: '2024-09-15T00:00:00.000Z',
            dueDate: '2024-10-31T00:00:00.000Z',
            actualStartDate: '2024-09-18T00:00:00.000Z',
            tags: 'PostMortem,RCA,Reliability',
          },
          {
            title: 'Await Facilities Disaster Drill Authorization from Building Management',
            description: 'Coordinate unannounced fire drill and power backup switch test with commercial building management authority.',
            priority: 'critical',
            status: 'pending_on_others',
            progress: 30,
            weight: 20,
            startDate: '2024-11-01T00:00:00.000Z',
            dueDate: '2024-12-10T00:00:00.000Z',
            tags: 'Facilities,Safety,Drill',
            dependencyRequiresManager: true,
            dependencyTitle: 'Waiting on Building Authority Safety Clearance & Date Allocation',
          },
          {
            title: 'Document Emergency Communications Playbook & Stakeholder WhatsApp Tree',
            description: 'Establish executive escalation bridge lines and customer status page templates for major incident communications.',
            priority: 'low',
            status: 'in_progress',
            progress: 60,
            weight: 20,
            startDate: '2024-12-10T00:00:00.000Z',
            dueDate: '2024-12-31T00:00:00.000Z',
            actualStartDate: '2024-12-12T00:00:00.000Z',
            tags: 'Communications,Crisis,Playbook',
          },
        ],
      },
    ],
    'FY 2025-26': [
      {
        goal: {
          title: 'Cross-Departmental SLA Governance & Operational Workflow Automation',
          description: 'Standardize ticket resolution turnaround times, automate task assignment rules, and cut operational handover cycle delays by 40%.',
          category: 'Business Operations',
          priority: 'high',
          goalType: 'General',
          status: 'COMPLETED',
          quarter: 'Q3',
          progress: 100,
          startDate: '2025-06-01T00:00:00.000Z',
          targetDate: '2025-12-31T00:00:00.000Z',
          dueDate: '2025-12-31T00:00:00.000Z',
          milestones: 4,
          completedMilestones: 4,
        },
        tasks: [
          {
            title: 'Map Enterprise Workflow Handoff Bottlenecks Across Units',
            description: 'Conduct interviews with team leads, document friction points in request routing, and quantify idle queue wait times.',
            priority: 'medium',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2025-06-10T00:00:00.000Z',
            dueDate: '2025-07-20T00:00:00.000Z',
            actualStartDate: '2025-06-12T00:00:00.000Z',
            actualCompletionDate: '2025-07-18T00:00:00.000Z',
            tags: 'Process,Mapping,Operations',
          },
          {
            title: 'Configure Auto-Escalation Engine for Stalled Operational Tickets',
            description: 'Define multi-tier notification rules to notify line managers after 48 hours and department heads after 72 hours of inactivity.',
            priority: 'high',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2025-07-25T00:00:00.000Z',
            dueDate: '2025-09-10T00:00:00.000Z',
            actualStartDate: '2025-07-28T00:00:00.000Z',
            actualCompletionDate: '2025-09-08T00:00:00.000Z',
            tags: 'Escalation,SLA,Automation',
          },
          {
            title: 'Conduct Quarterly Vendor SLA Performance & Compliance Audits',
            description: 'Review SLA uptime reports against contractual penalty terms and recommend contract adjustments for underperforming suppliers.',
            priority: 'medium',
            status: 'in_review',
            progress: 90,
            weight: 20,
            startDate: '2025-09-15T00:00:00.000Z',
            dueDate: '2025-10-31T00:00:00.000Z',
            actualStartDate: '2025-09-18T00:00:00.000Z',
            tags: 'Vendors,Contracts,SLA',
          },
          {
            title: 'Coordinate Enterprise Resource Capacity Planning Model with Leadership',
            description: 'Gather quarterly resource allocation forecasts and align staffing budgets with projected project milestones.',
            priority: 'critical',
            status: 'pending_on_others',
            progress: 35,
            weight: 20,
            startDate: '2025-11-01T00:00:00.000Z',
            dueDate: '2025-12-10T00:00:00.000Z',
            tags: 'Capacity,Planning,Staffing',
            dependencyRequiresManager: true,
            dependencyTitle: 'Waiting for Q4 Headcount Requisition Approvals from Executive Director',
          },
          {
            title: 'Roll Out Operations Knowledge Base & Standard Operating Procedures (SOP)',
            description: 'Publish vetted SOP checklists in Company Hub to onboard junior operations associates smoothly.',
            priority: 'low',
            status: 'todo',
            progress: 0,
            weight: 20,
            startDate: '2025-12-10T00:00:00.000Z',
            dueDate: '2025-12-31T00:00:00.000Z',
            tags: 'SOP,Training,Docs',
          },
        ],
      },
    ],
    'FY 2026-27': [
      {
        goal: {
          title: 'Asset Lifecycle Management & Facilities Carbon Footprint Reduction',
          description: 'Digitize physical asset tracking, implement energy audit schedules, and achieve a 15% reduction in facilities utility costs.',
          category: 'Business Operations',
          priority: 'medium',
          goalType: 'General',
          status: 'ACTIVE',
          quarter: 'Q2',
          progress: 40,
          startDate: '2026-04-01T00:00:00.000Z',
          targetDate: '2026-09-30T00:00:00.000Z',
          dueDate: '2026-09-30T00:00:00.000Z',
          milestones: 3,
          completedMilestones: 1,
        },
        tasks: [
          {
            title: 'Tag & Catalog All Fixed Hardware Assets with QR Code Tracking',
            description: 'Barcode every workstation, server rack, and display unit with serial numbers linked to the digital asset registry.',
            priority: 'medium',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2026-04-10T00:00:00.000Z',
            dueDate: '2026-05-20T00:00:00.000Z',
            actualStartDate: '2026-04-12T00:00:00.000Z',
            actualCompletionDate: '2026-05-18T00:00:00.000Z',
            tags: 'Assets,Hardware,Inventory',
          },
          {
            title: 'Perform Commercial Real Estate Energy Efficiency Baseline Audit',
            description: 'Partner with green audit consultant to measure HVAC kilowatt consumption and identify low-efficiency lighting units.',
            priority: 'high',
            status: 'in_progress',
            progress: 50,
            weight: 20,
            startDate: '2026-05-25T00:00:00.000Z',
            dueDate: '2026-07-15T00:00:00.000Z',
            actualStartDate: '2026-05-28T00:00:00.000Z',
            tags: 'Energy,Sustainability,Audit',
          },
          {
            title: 'Await Procurement Approval for Smart IoT Thermostats & Sensor Grid',
            description: 'Submit competitive vendor bids for smart temperature sensors to automate off-hours facility shutdowns.',
            priority: 'critical',
            status: 'pending_on_others',
            progress: 20,
            weight: 20,
            startDate: '2026-07-01T00:00:00.000Z',
            dueDate: '2026-08-15T00:00:00.000Z',
            tags: 'Procurement,IoT,SmartOffice',
            dependencyRequiresManager: true,
            dependencyTitle: 'Pending Green Tech Budget Allocation Clearance from Finance Team',
          },
          {
            title: 'Establish Preventive Maintenance Schedules for Critical Power Generators',
            description: 'Draft monthly generator run-tests, fuel inspection protocols, and battery health reporting schedules.',
            priority: 'medium',
            status: 'in_review',
            progress: 85,
            weight: 20,
            startDate: '2026-08-01T00:00:00.000Z',
            dueDate: '2026-09-10T00:00:00.000Z',
            actualStartDate: '2026-08-05T00:00:00.000Z',
            tags: 'Facilities,Maintenance,Power',
          },
          {
            title: 'Publish Comprehensive Sustainability & Corporate Governance Report',
            description: 'Compile quarterly energy reductions and carbon offset data for publication on company hub and investor deck.',
            priority: 'low',
            status: 'todo',
            progress: 0,
            weight: 20,
            startDate: '2026-09-10T00:00:00.000Z',
            dueDate: '2026-09-30T00:00:00.000Z',
            tags: 'ESG,Sustainability,Reporting',
          },
        ],
      },
    ],
  },

  HR: {
    'FY 2024-25': [
      {
        goal: {
          title: 'Digital HRIS Migration & Statutory Labor Law Compliance Overhaul',
          description: 'Digitize physical employee records into encrypted digital dossier vault, audit PF/ESI statutory contributions, and update employment contract templates.',
          category: 'Compliance & Security',
          priority: 'critical',
          goalType: 'General',
          status: 'COMPLETED',
          quarter: 'Q4',
          progress: 100,
          startDate: '2024-05-01T00:00:00.000Z',
          targetDate: '2025-03-31T00:00:00.000Z',
          dueDate: '2025-03-31T00:00:00.000Z',
          milestones: 4,
          completedMilestones: 4,
        },
        tasks: [
          {
            title: 'Digitize Physical Employee Dossiers & Establish Secure Vault Storage',
            description: 'Scan past employment letters, education proofs, and signed agreements into secure cloud S3 buckets with AES-256 encryption.',
            priority: 'high',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2024-05-10T00:00:00.000Z',
            dueDate: '2024-07-20T00:00:00.000Z',
            actualStartDate: '2024-05-12T00:00:00.000Z',
            actualCompletionDate: '2024-07-15T00:00:00.000Z',
            tags: 'HRIS,Digitization,Vault',
          },
          {
            title: 'Audit Statutory PF, ESI, and Gratuity Contributions Across Departments',
            description: 'Reconcile payroll deduction ledgers against government portal challans with external labor law compliance consultant.',
            priority: 'critical',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2024-07-25T00:00:00.000Z',
            dueDate: '2024-09-30T00:00:00.000Z',
            actualStartDate: '2024-07-28T00:00:00.000Z',
            actualCompletionDate: '2024-09-25T00:00:00.000Z',
            tags: 'Compliance,PF,ESI,Audit',
          },
          {
            title: 'Draft Enterprise Remote Work & Flexible Hours Policy Document',
            description: 'Define core collaboration hours, home office stipend guidelines, and communication response expectations in Policy Hub.',
            priority: 'medium',
            status: 'in_review',
            progress: 90,
            weight: 20,
            startDate: '2024-10-01T00:00:00.000Z',
            dueDate: '2024-11-25T00:00:00.000Z',
            actualStartDate: '2024-10-05T00:00:00.000Z',
            tags: 'Policy,RemoteWork,HR',
          },
          {
            title: 'Await External Legal Counsel Review on Revised Employment Contracts',
            description: 'Review updated confidentiality, non-compete, and intellectual property assignment covenants with external corporate attorneys.',
            priority: 'critical',
            status: 'pending_on_others',
            progress: 35,
            weight: 20,
            startDate: '2024-12-01T00:00:00.000Z',
            dueDate: '2025-01-20T00:00:00.000Z',
            tags: 'Contracts,Legal,Employment',
            dependencyRequiresManager: true,
            dependencyTitle: 'Waiting on Corporate Law Firm Retainer Feedback on IP Clauses',
          },
          {
            title: 'Conduct POSH Annual Awareness Workshops for All Staff Members',
            description: 'Host mandatory Prevention of Sexual Harassment (POSH) training sessions, certify Internal Committee members, and publish annual report.',
            priority: 'low',
            status: 'todo',
            progress: 0,
            weight: 20,
            startDate: '2025-02-01T00:00:00.000Z',
            dueDate: '2025-03-31T00:00:00.000Z',
            tags: 'POSH,Compliance,Training',
          },
        ],
      },
    ],
    'FY 2025-26': [
      {
        goal: {
          title: 'Organization Talent Retention & Employee Experience Modernization',
          description: 'Implement structured career growth ladders, reduce first-year employee attrition by 25%, and automate 360-degree feedback reviews.',
          category: 'Leadership & Management',
          priority: 'critical',
          goalType: 'General',
          status: 'COMPLETED',
          quarter: 'Q4',
          progress: 100,
          startDate: '2025-05-01T00:00:00.000Z',
          targetDate: '2026-03-31T00:00:00.000Z',
          dueDate: '2026-03-31T00:00:00.000Z',
          milestones: 4,
          completedMilestones: 4,
        },
        tasks: [
          {
            title: 'Design Standardized Engineering & Operations Career Competency Bands',
            description: 'Define clear seniority expectations, promotion criteria, and salary compensation benchmark ranges.',
            priority: 'high',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2025-05-10T00:00:00.000Z',
            dueDate: '2025-07-15T00:00:00.000Z',
            actualStartDate: '2025-05-12T00:00:00.000Z',
            actualCompletionDate: '2025-07-10T00:00:00.000Z',
            tags: 'HR,Competency,Compensation',
          },
          {
            title: 'Deploy Automated Digital Onboarding Portal & Document Verification',
            description: 'Integrate Aadhaar/PAN verification, digital PF compliance forms, and automated welcome kit fulfillment.',
            priority: 'medium',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2025-07-20T00:00:00.000Z',
            dueDate: '2025-09-30T00:00:00.000Z',
            actualStartDate: '2025-07-22T00:00:00.000Z',
            actualCompletionDate: '2025-09-28T00:00:00.000Z',
            tags: 'Onboarding,Compliance,Automation',
          },
          {
            title: 'Conduct Mid-Year Employee Pulse Engagement & Wellbeing Survey',
            description: 'Analyze anonymous feedback responses on work-life balance, manager support, and workplace safety satisfaction.',
            priority: 'medium',
            status: 'in_review',
            progress: 90,
            weight: 20,
            startDate: '2025-10-01T00:00:00.000Z',
            dueDate: '2025-11-20T00:00:00.000Z',
            actualStartDate: '2025-10-05T00:00:00.000Z',
            tags: 'PulseSurvey,Engagement,Wellbeing',
          },
          {
            title: 'Await Executive Committee Approval on Annual Variable Incentive Scheme',
            description: 'Formulate bonus multiplier formulas linked to department target achievement percentages.',
            priority: 'critical',
            status: 'pending_on_others',
            progress: 30,
            weight: 20,
            startDate: '2025-12-01T00:00:00.000Z',
            dueDate: '2026-01-20T00:00:00.000Z',
            tags: 'Bonus,Incentives,Executive',
            dependencyRequiresManager: true,
            dependencyTitle: 'Waiting for Compensation Committee Final Sign-off on Variable Pool',
          },
          {
            title: 'Execute Annual Appraisal Calibration Cycles & Promotion Letters',
            description: 'Facilitate department manager review sessions, normalize rating bell curves, and distribute increment letters.',
            priority: 'high',
            status: 'todo',
            progress: 0,
            weight: 20,
            startDate: '2026-02-01T00:00:00.000Z',
            dueDate: '2026-03-31T00:00:00.000Z',
            tags: 'Appraisal,Promotions,Calibration',
          },
        ],
      },
    ],
    'FY 2026-27': [
      {
        goal: {
          title: 'Leadership Development & High-Potential Mentorship Accelerator',
          description: 'Establish executive coaching circles, sponsor professional certifications, and cultivate next-generation tech leaders.',
          category: 'Learning & Development',
          priority: 'high',
          goalType: 'General',
          status: 'ACTIVE',
          quarter: 'Q1',
          progress: 35,
          startDate: '2026-04-01T00:00:00.000Z',
          targetDate: '2026-09-30T00:00:00.000Z',
          dueDate: '2026-09-30T00:00:00.000Z',
          milestones: 3,
          completedMilestones: 1,
        },
        tasks: [
          {
            title: 'Identify High-Potential (HiPo) Associates via 9-Box Grid Assessment',
            description: 'Evaluate individual performance vs potential ratings with business unit heads to select cohort participants.',
            priority: 'medium',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2026-04-10T00:00:00.000Z',
            dueDate: '2026-05-15T00:00:00.000Z',
            actualStartDate: '2026-04-12T00:00:00.000Z',
            actualCompletionDate: '2026-05-12T00:00:00.000Z',
            tags: '9Box,HiPo,Talent',
          },
          {
            title: 'Pair Mentors and Mentees Across Engineering & Business Divisions',
            description: 'Establish bi-weekly coaching cadence, mutual expectation contracts, and milestone tracking diaries.',
            priority: 'medium',
            status: 'in_progress',
            progress: 50,
            weight: 20,
            startDate: '2026-05-16T00:00:00.000Z',
            dueDate: '2026-06-30T00:00:00.000Z',
            actualStartDate: '2026-05-20T00:00:00.000Z',
            tags: 'Mentorship,Coaching,Leadership',
          },
          {
            title: 'Await L&D Budget Allocation for External Executive Certification Programs',
            description: 'Secure corporate group discounts for Cloud Architecture & Certified Scrum Master certification vouchers.',
            priority: 'critical',
            status: 'pending_on_others',
            progress: 15,
            weight: 20,
            startDate: '2026-06-15T00:00:00.000Z',
            dueDate: '2026-07-25T00:00:00.000Z',
            tags: 'Certifications,Budget,Training',
            dependencyRequiresManager: true,
            dependencyTitle: 'Pending Executive Training Budget Approval from Head of Finance',
          },
          {
            title: 'Host Quarterly Leadership Fireside Chat with Industry Founders',
            description: 'Organize interactive virtual session on building resilient products at hyperscale with Q&A panel.',
            priority: 'low',
            status: 'in_review',
            progress: 75,
            weight: 20,
            startDate: '2026-07-20T00:00:00.000Z',
            dueDate: '2026-08-20T00:00:00.000Z',
            actualStartDate: '2026-07-22T00:00:00.000Z',
            tags: 'Events,Culture,Fireside',
          },
          {
            title: 'Review Mid-Program Learning Outcomes & Mentee Project Deliverables',
            description: 'Assess strategic problem-solving proposals submitted by mentee teams and award implementation grants.',
            priority: 'medium',
            status: 'todo',
            progress: 0,
            weight: 20,
            startDate: '2026-08-25T00:00:00.000Z',
            dueDate: '2026-09-30T00:00:00.000Z',
            tags: 'Outcomes,Evaluation,Grants',
          },
        ],
      },
    ],
  },

  Finance: {
    'FY 2024-25': [
      {
        goal: {
          title: 'Enterprise Financial Ledger Migration & Multi-Currency Accounting',
          description: 'Migrate legacy accounting ledgers to cloud ERP, establish multi-currency exchange rate sync, and close year-end financial books smoothly.',
          category: 'Business Operations',
          priority: 'critical',
          goalType: 'General',
          status: 'COMPLETED',
          quarter: 'Q4',
          progress: 100,
          startDate: '2024-04-01T00:00:00.000Z',
          targetDate: '2025-03-31T00:00:00.000Z',
          dueDate: '2025-03-31T00:00:00.000Z',
          milestones: 4,
          completedMilestones: 4,
        },
        tasks: [
          {
            title: 'Migrate Historical Journal Entries to Enterprise ERP General Ledger',
            description: 'Import 3 fiscal years of historical debit/credit transactions and verify opening trial balance balance parity.',
            priority: 'critical',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2024-04-10T00:00:00.000Z',
            dueDate: '2024-06-15T00:00:00.000Z',
            actualStartDate: '2024-04-12T00:00:00.000Z',
            actualCompletionDate: '2024-06-10T00:00:00.000Z',
            tags: 'ERP,Ledger,Migration',
          },
          {
            title: 'Implement Automated Forex Gain/Loss Calculation for Foreign Invoices',
            description: 'Configure real-time RBI currency exchange feeds and automate unrealized gain/loss postings at month-end closing.',
            priority: 'high',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2024-06-20T00:00:00.000Z',
            dueDate: '2024-08-31T00:00:00.000Z',
            actualStartDate: '2024-06-25T00:00:00.000Z',
            actualCompletionDate: '2024-08-28T00:00:00.000Z',
            tags: 'Forex,Accounting,MultiCurrency',
          },
          {
            title: 'Establish Internal Financial Controls (IFC) Framework & Segregation of Duties',
            description: 'Audit maker-checker permissions in payment release systems to eliminate single-point fraud vulnerabilities.',
            priority: 'medium',
            status: 'in_review',
            progress: 85,
            weight: 20,
            startDate: '2024-09-01T00:00:00.000Z',
            dueDate: '2024-10-31T00:00:00.000Z',
            actualStartDate: '2024-09-05T00:00:00.000Z',
            tags: 'IFC,Controls,Governance',
          },
          {
            title: 'Coordinate Annual Transfer Pricing Documentation with External Advisors',
            description: 'Compile inter-company transaction benchmarking study and form 3CEB filing annexures with Big 4 tax consultant.',
            priority: 'critical',
            status: 'pending_on_others',
            progress: 20,
            weight: 20,
            startDate: '2024-11-01T00:00:00.000Z',
            dueDate: '2025-01-15T00:00:00.000Z',
            tags: 'TransferPricing,Tax,3CEB',
            dependencyRequiresManager: true,
            dependencyTitle: 'Awaiting Transfer Pricing Study Certification from External Tax Partner',
          },
          {
            title: 'Compile FY 2024-25 Comprehensive Audit File for Board Presentation',
            description: 'Finalize profit and loss statement, cash flow statement, and balance sheet notes for board approval.',
            priority: 'high',
            status: 'todo',
            progress: 0,
            weight: 20,
            startDate: '2025-01-20T00:00:00.000Z',
            dueDate: '2025-03-31T00:00:00.000Z',
            tags: 'Audit,Financials,Board',
          },
        ],
      },
    ],
    'FY 2025-26': [
      {
        goal: {
          title: 'Automated Financial Invoicing, GST Compliance & Audit Readiness',
          description: 'Implement real-time electronic invoicing, automate input tax credit reconciliation, and achieve zero-defect statutory audit report.',
          category: 'Business Operations',
          priority: 'critical',
          goalType: 'General',
          status: 'COMPLETED',
          quarter: 'Q4',
          progress: 100,
          startDate: '2025-04-01T00:00:00.000Z',
          targetDate: '2026-03-31T00:00:00.000Z',
          dueDate: '2026-03-31T00:00:00.000Z',
          milestones: 4,
          completedMilestones: 4,
        },
        tasks: [
          {
            title: 'Integrate E-Invoicing API with Government IRP Portal',
            description: 'Generate Invoice Reference Number (IRN) and signed QR code automatically for B2B billing operations.',
            priority: 'critical',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2025-04-10T00:00:00.000Z',
            dueDate: '2025-06-15T00:00:00.000Z',
            actualStartDate: '2025-04-12T00:00:00.000Z',
            actualCompletionDate: '2025-06-10T00:00:00.000Z',
            tags: 'EInvoicing,GST,IRP',
          },
          {
            title: 'Deploy Automated Bank Reconciliation Engine with Multi-Bank Feeds',
            description: 'Match incoming customer NEFT/RTGS payments against open accounts receivable with 98% auto-matching accuracy.',
            priority: 'high',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2025-06-20T00:00:00.000Z',
            dueDate: '2025-08-31T00:00:00.000Z',
            actualStartDate: '2025-06-25T00:00:00.000Z',
            actualCompletionDate: '2025-08-28T00:00:00.000Z',
            tags: 'Banking,Reconciliation,Finance',
          },
          {
            title: 'Conduct Comprehensive Mid-Year Operating Budget Variance Analysis',
            description: 'Compare actual cloud infrastructure and departmental overhead spend against initial annual budget forecasts.',
            priority: 'medium',
            status: 'in_review',
            progress: 90,
            weight: 20,
            startDate: '2025-09-01T00:00:00.000Z',
            dueDate: '2025-10-31T00:00:00.000Z',
            actualStartDate: '2025-09-05T00:00:00.000Z',
            tags: 'Variance,Budget,Forecasting',
          },
          {
            title: 'Coordinate Annual Statutory Tax Audit Schedule & Working Papers',
            description: 'Prepare fixed asset register, depreciation schedules, and tax deduction (TDS) certificates for external auditors.',
            priority: 'critical',
            status: 'pending_on_others',
            progress: 35,
            weight: 20,
            startDate: '2025-11-01T00:00:00.000Z',
            dueDate: '2026-01-15T00:00:00.000Z',
            tags: 'Tax,Audit,TDS',
            dependencyRequiresManager: true,
            dependencyTitle: 'Waiting on External Statutory Auditor Engagement Letter Confirmation',
          },
          {
            title: 'Finalize Annual Fiscal Year Closing Balances & Audited Financial Statements',
            description: 'Complete trial balance adjustments, provisions for doubtful debts, and board balance sheet annexures.',
            priority: 'high',
            status: 'todo',
            progress: 0,
            weight: 20,
            startDate: '2026-01-20T00:00:00.000Z',
            dueDate: '2026-03-31T00:00:00.000Z',
            tags: 'YearEnd,Financials,BalanceSheet',
          },
        ],
      },
    ],
    'FY 2026-27': [
      {
        goal: {
          title: 'Automated Vendor Expense Management & Travel Reimbursement Modernization',
          description: 'Deploy OCR-assisted expense voucher processing, enforce policy limit controls, and reduce reimbursement payment turnaround to 48 hours.',
          category: 'Performance & Delivery',
          priority: 'high',
          goalType: 'General',
          status: 'ACTIVE',
          quarter: 'Q1',
          progress: 50,
          startDate: '2026-04-01T00:00:00.000Z',
          targetDate: '2026-09-30T00:00:00.000Z',
          dueDate: '2026-09-30T00:00:00.000Z',
          milestones: 3,
          completedMilestones: 1,
        },
        tasks: [
          {
            title: 'Deploy OCR Optical Character Recognition for Employee Travel Bills',
            description: 'Extract date, merchant GSTIN, and gross amounts from uploaded receipt images to eliminate manual data entry.',
            priority: 'medium',
            status: 'done',
            progress: 100,
            weight: 20,
            startDate: '2026-04-05T00:00:00.000Z',
            dueDate: '2026-05-15T00:00:00.000Z',
            actualStartDate: '2026-04-08T00:00:00.000Z',
            actualCompletionDate: '2026-05-12T00:00:00.000Z',
            tags: 'OCR,Expenses,Automation',
          },
          {
            title: 'Configure Multi-Tier Manager Approval Rules by Expense Amount',
            description: 'Enforce automatic approval under INR 2,000, line manager approval up to INR 25,000, and CFO sign-off above.',
            priority: 'high',
            status: 'in_progress',
            progress: 55,
            weight: 20,
            startDate: '2026-05-16T00:00:00.000Z',
            dueDate: '2026-06-30T00:00:00.000Z',
            actualStartDate: '2026-05-18T00:00:00.000Z',
            tags: 'ApprovalFlow,Policies,Controls',
          },
          {
            title: 'Integrate Corporate Credit Card Direct Bank Statement Feed API',
            description: 'Automatically pull daily corporate card cardholder statements for automated expense pre-population.',
            priority: 'critical',
            status: 'pending_on_others',
            progress: 25,
            weight: 20,
            startDate: '2026-06-15T00:00:00.000Z',
            dueDate: '2026-07-31T00:00:00.000Z',
            tags: 'CreditCard,Integration,Banking',
            dependencyRequiresManager: true,
            dependencyTitle: 'Awaiting Bank Open-Banking Corporate API Access Keys',
          },
          {
            title: 'Conduct Employee Expense Policy Briefing & FAQ Webinar',
            description: 'Host interactive session covering eligible per-diem allowances, eligible hotel bookings, and travel insurance.',
            priority: 'low',
            status: 'in_review',
            progress: 80,
            weight: 20,
            startDate: '2026-07-20T00:00:00.000Z',
            dueDate: '2026-08-25T00:00:00.000Z',
            actualStartDate: '2026-07-22T00:00:00.000Z',
            tags: 'Webinar,Policy,Training',
          },
          {
            title: 'Publish Monthly Expense Analytics & Overspend Anomaly Report',
            description: 'Provide department heads with category breakdowns of travel, software SaaS, and team dinner expenses.',
            priority: 'medium',
            status: 'todo',
            progress: 0,
            weight: 20,
            startDate: '2026-08-25T00:00:00.000Z',
            dueDate: '2026-09-30T00:00:00.000Z',
            tags: 'Analytics,Reporting,Budget',
          },
        ],
      },
    ],
  },
};
